sudo: required

services:
  - docker

before_install:
  - docker build -t hammadallauddin/docker-react -f Dockerfile.dev .

script:
  - docker run hammadallauddin/docker-react npm run test -- --coverage